export const APIS_ROUTES = {
  SIGNIN: "/auth/v1/user/signin",
  REFRESH_TOKEN: "/auth/v1/user/refresh-token",
  LOGOUT: "/auth/v1/user/logout",
  UPDATE_USER_PREFERENCES: "/auth/v1/user/preferences",
  UPLOAD_AVATAR: "/auth/v1/user/avatar",
  UPDATE_MY_PROFILE: "/auth/v1/user/profile",
  CHANGE_MY_PASSWORD: "/auth/v1/user/change-password",
  FORGOT_PASSWORD: "/auth/v1/user/forgot-password",
  RESET_PASSWORD: "/auth/v1/user/reset-password/:token",
  SET_USER_PASSWORD: "/auth/v1/user/set-user-password",
  GET_USER_DETAILS: "/auth/v1/user/get-user-details",
  ADD_USER: "/auth/v1/user/add-user",
  GET_ALL_USER: "/auth/v1/user/get-all-users",
  STUDENT_PROFILE: "/student-service/v1/profile",
  UPDATE_USER_DETAILS: "/auth/v1/user/update-user-details",
  DELETE_USER: "/auth/v1/user/delete-user",
  ORGANIZATION_SERVICE: "/organization-service/v1/organization",
  SCHOOL_SERVICE: "/school-service/v1",
  AI_SERVICE: "/ai-service/v1/generate-content",
  ACADEMIC_SERVICE: "/academic-service/v1",
  DASHBOARD_SERVICE: "/dashboard-service/v1",
  STAFF_SERVICE: "/staff-service/v1",
  ATTENDANCE_SERVICE: "/attendance-service/v1",
  HOMEWORK_SERVICE: "/homework-service/v1",
  PTM_SERVICE: "/ptm-service/v1",
  FEE_SERVICE: "/fee-service/v1",
  EXAM_SERVICE: "/exam-service/v1",
  LEAVE_SERVICE: "/leave-service/v1",
};

export const API_QUERY_KEY = {
  GET_MODEL_STATISTICS_PERSONALIZATION: "get-model-statistics-personalization",
  GET_USER_DETAILS: "get-user-details",
  GET_ALL_USER: "get-all-user",
  GET_STUDENT_PROFILE: "get-student-profile",
  GET_ALL_ORGANIZATIONS: "get-all-organizations",
  GET_PARENT_DETAILS: "get-parent-details",
  GET_STUDENT_BY_ID: "get-student-by-id",
  GET_NOTICE_LIST: "get-notice-list",
  AI_CONTENT: "get-ai-content",
  GET_ACADEMIC_YEARS: "get-academic-years",
  GET_CLASSES: "get-classes",
  GET_SECTIONS: "get-sections",
  GET_SUBJECTS: "get-subjects",
  GET_TEACHER_ASSIGNMENTS: "get-teacher-assignments",
  GET_ALL_TEACHERS: "get-all-teachers",
  GET_DASHBOARD_STATS: "get-dashboard-stats",
  GET_DASHBOARD_CHARTS: "get-dashboard-charts",
  GET_PARENT_DASHBOARD: "get-parent-dashboard",
  GET_TEACHER_DIRECTORY: "get-teacher-directory",
  GET_SECTION_ATTENDANCE: "get-section-attendance",
  GET_SECTION_ATTENDANCE_REPORT: "get-section-attendance-report",
  GET_HOMEWORK_LIST: "get-homework-list",
  GET_MY_TEACHING_LOAD: "get-my-teaching-load",
  GET_MY_NOTICES: "get-my-notices",
  GET_MY_NOTIFICATIONS: "get-my-notifications",
  GET_PTM_EVENTS: "get-ptm-events",
  GET_PTM_SLOTS: "get-ptm-slots",
  GET_MY_PTM_BOOKINGS: "get-my-ptm-bookings",
  GET_MY_PTM_AGENDA: "get-my-ptm-agenda",
  GET_FEE_HEADS: "get-fee-heads",
  GET_FEE_STRUCTURES: "get-fee-structures",
  GET_STUDENT_FEE_SUMMARY: "get-student-fee-summary",
  GET_MY_FEES: "get-my-fees",
  GET_PAYMENT_LEDGER: "get-payment-ledger",
  GET_GRADING_SCHEMES: "get-grading-schemes",
  GET_EXAMS: "get-exams",
  GET_EXAM_SUBJECTS: "get-exam-subjects",
  GET_MARKS_SHEET: "get-marks-sheet",
  GET_RESULTS_FOR_STUDENT: "get-results-for-student",
  GET_MY_RESULTS: "get-my-results",
  GET_MY_LEAVE_REQUESTS: "get-my-leave-requests",
  GET_LEAVE_REQUESTS_REVIEW_QUEUE: "get-leave-requests-review-queue",
  GET_PROMOTION_CANDIDATES: "get-promotion-candidates",
  GET_ALL_ACCOUNTS: "get-all-accounts",
};

export const API_MUTATION_KEY = {
  SIGNIN: "signin",
  FORGOT_PASSWORD: "forgot-password",
  RESET_PASSWORD: "reset-password",
  SET_USER_PASSWORD: "set-user-password",
  ADD_USER: "add-user",
  ADD_STUDENT_PROFILE: "add-student-profile",
  UPDATE_USER_DETAILS: "update-user-details",
  DELETE_USER: "delete-user",
  UPDATE_STUDENT_DETAILS: "update-student-details",
  DELETE_STUDENT: "delete-student",
  CREATE_NOTICE: "create-notice",
  CREATE_HOMEWORK: "create-homework",
  DELETE_HOMEWORK: "delete-homework",
  DELETE_NOTICE: "delete-notice",
  CREATE_ORGANIZATION: "create-organization",
  UPDATE_ORGANIZATION: "update-organization",
  CREATE_ACADEMIC_YEAR: "create-academic-year",
  CREATE_CLASS: "create-class",
  CREATE_SECTION: "create-section",
  CREATE_SUBJECT: "create-subject",
  ASSIGN_TEACHER: "assign-teacher",
  MARK_NOTICE_READ: "mark-notice-read",
  MARK_NOTIFICATION_READ: "mark-notification-read",
  MARK_ALL_NOTIFICATIONS_READ: "mark-all-notifications-read",
  CREATE_PTM_EVENT: "create-ptm-event",
  GENERATE_PTM_SLOTS: "generate-ptm-slots",
  BOOK_PTM_SLOT: "book-ptm-slot",
  CANCEL_PTM_BOOKING: "cancel-ptm-booking",
  CREATE_FEE_HEAD: "create-fee-head",
  CREATE_FEE_STRUCTURE: "create-fee-structure",
  ASSIGN_FEE_STRUCTURE: "assign-fee-structure",
  RECORD_PAYMENT: "record-payment",
  REVERSE_PAYMENT: "reverse-payment",
  GRANT_CONCESSION: "grant-concession",
  EMAIL_FEE_RECEIPT: "email-fee-receipt",
  EMAIL_REPORT_CARD: "email-report-card",
  CREATE_GRADING_SCHEME: "create-grading-scheme",
  CREATE_EXAM: "create-exam",
  ADD_EXAM_SUBJECTS: "add-exam-subjects",
  SAVE_MARKS: "save-marks",
  VERIFY_EXAM_SUBJECT_MARKS: "verify-exam-subject-marks",
  PUBLISH_EXAM: "publish-exam",
  UPDATE_USER_PREFERENCES: "update-user-preferences",
  UPDATE_MY_PROFILE: "update-my-profile",
  CHANGE_MY_PASSWORD: "change-my-password",
  UPLOAD_ORGANIZATION_LOGO: "upload-organization-logo",
  UPLOAD_AVATAR: "upload-avatar",
  CREATE_LEAVE_REQUEST: "create-leave-request",
  CANCEL_LEAVE_REQUEST: "cancel-leave-request",
  DECIDE_LEAVE_REQUEST: "decide-leave-request",
  CREATE_ACCOUNT: "create-account",
  ADD_ORGANIZATION_TO_ACCOUNT: "add-organization-to-account",
  UPDATE_ACCOUNT_STATUS: "update-account-status",
};

export const GOOGLE_CAPTCHA_KEY = "6LeCtSorAAAAAN38EwKA3qBHzEWYsx6is3RT8eSa";

export const EMAIL_REGEX_PATTERN = new RegExp(/^[a-zA-Z0-9._+-]+@([a-zA-Z0-9.-]+\.[a-zA-Z]{2,10})$/i);

export const USER_ACCESS_KEY = {
  TOKEN: "kidSightAccessToken",
  REFRESH_TOKEN: "kidSightRefreshToken",
  ROLE: "kidSightUserRole",
  ORGANIZATION_ID: "kidSightOrganizationId",
  ORGANIZATION_NAME: "kidSightOrganizationName",
};

export const TOTAL_STEPS = 2;
